after_success:
- bash <(curl -s https://codecov.io/bash)
- python mvn_settings.py
before_install:
- wget http://www.deflaker.org/maven/apache-maven-3.3.9.zip
- unzip -qq apache-maven-3.3.9.zip
- export M2_HOME=$PWD/apache-maven-3.3.9
- export PATH=$M2_HOME/bin:$PATH
- export TZ=Asia/Shanghai
before_script:
- psql -c 'create database nutztest;' -U postgres
- cp ./tools/travis-ci/nutz-test.properties ./test/
- cp ./tools/travis-ci/log4j.properties ./test/
language: java
jdk:
  - oraclejdk8
# whitelist
branches:
  only:
  - master
  - coverity_scan
jdk:
- oraclejdk8
language: java
notifications:
  email: false
  slack:
    rooms: flakycov:U2MeVOPjdi4up1U793ubeIUZ
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}
    - 'dashbot: %{repository_name} %{build_id}'
script: mvn clean source:jar package
sudo: false
addons:
  postgresql: "9.3"
